name: Push image to AWS
on:
  workflow_run:
    workflows: ["Login to AWS and build image"]
    branches: [main]
    types: 
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    steps:
        #Push the image to AWS ECR
      - name: Push the image to Amazon ECR
        id: push-image
        uses: ./.github/workflows/deploy-to-aws.yml
      - run: 
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG